/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.s2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrameMain extends javax.swing.JFrame{

    /**
     * Creates new form FrameMain
     */
    public FrameMain() {
        initComponents();
        setTanggal();
    }
    
    int harga;
    int id;
    
    
    public void pilihBuku(){
        if(jComboBox1.getSelectedItem()== "Sejarah Indonesia BSE"){
            harga = 35000;
            id = 1;
        }else if(jComboBox1.getSelectedItem() == "Bahasa Indonesia BSE"){
            harga = 38000;
            id = 2;
        }else if(jComboBox1.getSelectedItem() == "Pendidikan Kewarganegaraan BSE"){
            harga = 40000;
            id = 3;
        }else if(jComboBox1.getSelectedItem() == "Bahasa Jawa"){
            harga = 36000;
            id = 4;
        }
    }   
    
    public void setTanggal(){//method untuk menampilkan tanggal
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        lbTanggal.setText(kal.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbTanggal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfNamaKasir = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        tfDiskon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BO OK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 190, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MiniMart");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 240, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/s2/logoMM.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 200, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("InsyaAllah Berkah.....");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 270, 120, 30);

        lbTanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbTanggal.setText("Tanggal");
        jPanel1.add(lbTanggal);
        lbTanggal.setBounds(170, 420, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setText("Syariah");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 240, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 450);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("List Transaksi >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(100, 60, 190, 30);

        jButton4.setBackground(new java.awt.Color(255, 102, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(270, 10, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 10, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(270, 340, 390, 110);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel4.setText("Nama Kasir");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 30, 120, 30);

        tfNamaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaKasirActionPerformed(evt);
            }
        });
        jPanel3.add(tfNamaKasir);
        tfNamaKasir.setBounds(140, 30, 200, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Sejarah Indonesia BSE", "Bahasa Indonesia BSE", "Pendidikan Kewarganegaraan BSE", "Bahasa Jawa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(140, 70, 200, 30);

        jLabel6.setText("Nama Barang");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 70, 100, 30);

        jLabel7.setText("Jumlah Barang");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 110, 110, 30);

        tfJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahActionPerformed(evt);
            }
        });
        jPanel3.add(tfJumlah);
        tfJumlah.setBounds(140, 110, 200, 30);

        tfDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiskonActionPerformed(evt);
            }
        });
        jPanel3.add(tfDiskon);
        tfDiskon.setBounds(140, 150, 50, 30);

        jLabel3.setText("%");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 150, 30, 30);

        jLabel8.setText("Diskon");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 150, 80, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(270, 0, 390, 340);

        setBounds(0, 0, 674, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaKasirActionPerformed

    private void tfJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahActionPerformed

    private void tfDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiskonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new List().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if("".equals(tfNamaKasir.getText()) || "--".equals(jComboBox1.getSelectedItem())
                || "".equals(tfJumlah.getText()) || "".equals(tfDiskon.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            pilihBuku();
            int jml_brg = Integer.parseInt(tfJumlah.getText());
            int total = harga * jml_brg;
            int diskon = Integer.parseInt(tfDiskon.getText());
            int harga_final = total - (total * diskon/100);
            
            String sql = "INSERT INTO tb_transaksi(id_barang, nama_barang, harga_satuan, jumlah_barang, total_harga, diskon, harga_final, nama_kasir)"
                    + "VALUES('"+id
                    +"', '"+jComboBox1.getSelectedItem().toString()
                    +"', '"+harga
                    +"', '"+tfJumlah.getText()
                    +"', '"+String.valueOf(total)
                    +"', '"+tfDiskon.getText()
                    +"', '"+String.valueOf(harga_final)
                    +"', '"+tfNamaKasir.getText()+"')";
            
            int status = KoneksiDB.execute(sql);
            
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
                    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tfNamaKasir.setText("");
        jComboBox1.setSelectedIndex(0);
        tfDiskon.setText("");
        tfJumlah.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JTextField tfDiskon;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNamaKasir;
    // End of variables declaration//GEN-END:variables

    
}
